# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('estimated_start_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ('-start_date',)},
        ),
    ]
